@baseUrl = http://localhost:3000


### List all categories
# @name ListAllCategories
GET {{baseUrl}}/categories

### Find one category
# @name FindOneCategory
GET {{baseUrl}}/categories/1

### Create category
# @name CreateCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Mecânica"
}

### Update category
# @name UpdateCategory
PATCH {{baseUrl}}/categories/1
Content-Type: application/json

{
    "name": "Mecânica"
}

### Delete category
# @name UpdateCategory
DELETE {{baseUrl}}/categories/2


### List all tasks
# @name ListAllTasks
GET {{baseUrl}}/tasks

### Find one task
# @name FindOneTask
GET {{baseUrl}}/tasks/2

### Create task
# @name CreateTask
POST {{baseUrl}}/tasks
Content-Type: application/json

{
    "title": "Tarefa 02",
    "description": "Descrição teste aqui",
    "status": "PENDING",
    "category_id": 1
}

### Update task
# @name UpdateTask
PATCH {{baseUrl}}/tasks/2
Content-Type: application/json

{
    "category_id": 2
}

### Delete task
# @name DeleteTask
DELETE {{baseUrl}}/tasks/1